### ISSUE TITLE
import signal module to AppConfig

### ISSUE THREAD

**Issue by namwoo-andreea** [PacktPublishing/Django-2-by-Example#1]
Django-2-by-Example/Chapter06/bookmarks/images/apps.py

The signal module has to be imported in `AppConfig.__init__()` method, not `AppConfig.ready()` method. Otherwise, the m2m_changed signal is not triggered.

Here is Django official documentation, 
https://docs.djangoproject.com/en/2.0/ref/signals/#class-prepared

**Comment by praju89** [comment]
Thank you namwoo-andreea for the information. We will update the same on our website.
