### ISSUE TITLE
Chapter 9 | Extending the admin site with custom views | admin.css

### ISSUE THREAD

**Issue by bjaus** [PacktPublishing/Django-2-by-Example#11]
In Chapter 9 you reference a ```static/``` directory for the ```orders``` application...

<img width="632" alt="image" src="https://user-images.githubusercontent.com/13722050/52913573-f50f4000-3284-11e9-9616-e9a721c047b8.png">

...but you do not have that pushed to GitHub.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/13722050/52913613-3e5f8f80-3285-11e9-8878-cde1d24dda3d.png">

Could you please add it or advise how I can access these static files. Specifically ```admin.css``` as that is the one that I'm specifically needing now. However, I'm not sure if any other static assets are mentioned later in this course.

Thank you!

**Comment by ohotnikoff** [comment]
Change {% static 'css/admin.css' %} to {% static "admin/css/base.css" %}

https://github.com/PacktPublishing/Django-2-by-Example/blob/master/Chapter08/myshop/static/admin/css/base.css
