### ISSUE TITLE
Chapter01 an error in list.html 

### ISSUE THREAD

**Issue by ns68** [PacktPublishing/Django-2-by-Example#19]
A syntactic error in list.html @ line #7: {% for post in post %}
Must be: {% for post in posts %}

**Comment by rahul7011** [comment]
yes! there's an error but someone already requested a pull request for this issue.. u can check pull request#16 so need to open a new issue request for this one.

**Comment by okidijimmy200** [comment]
Hey guy, am having issues with {% for post in posts %}, it doesnot display anything from  the database

**Comment by ejk3052** [comment]
Hi , I also have the issue with list view. I followed the instructions. It looks for detail view and I have not created the detail view. When i set one post to publish and then look at the site, it throws error. The if all are in draft the Html page does show up.

The error:


Request Method: | GET
-- | --
http://127.0.0.1:8000/blog/
3.0.6
NoReverseMatch
Reverse for 'post_detail' not found. 'post_detail' is not a valid view function or pattern name.
/Users/jayakumare/pusth-site/pusth_env/lib/python3.8/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 677
