### ISSUE TITLE
In capter1, the page can't show detail and list?

### ISSUE THREAD

**Issue by fangchaooo** [PacktPublishing/Django-2-by-Example#2]
I download the code and do this
```python 
python manage.py migrate

python manage.py createsuperuser
# input admin and password
```
Then create two post on admin. But the page won't show detail and list

![blog](https://user-images.githubusercontent.com/19619745/41894269-f861cf54-7950-11e8-806a-1a3579c016dd.png)

**Comment by praju89** [comment]
Hi Fang,

Did you try publishing the post?
Try it and let me know if it works.

Thank you

**Comment by fangchaooo** [comment]
oh......It's my fault.
I choose my post to publishing and it works

Thank you
