### ISSUE TITLE
Chapter 02 an error in views.py "name 'send_mail' is not defined"

### ISSUE THREAD

**Issue by alankaupervud** [PacktPublishing/Django-2-by-Example#20]
I have the error: "name 'send_mail' is not defined" in this part of code:
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST' :
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading"{}"'.format(cd['name'],cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'],cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
        return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent' : sent})

How to fix this error?

**Comment by hippieZhou** [comment]
First，you should config your email services for your website, example

```bash
# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '1736252185@qq.com'
EMAIL_HOST_PASSWORD = 'xxxxxxxxxx'
EMAIL_USE_TLS = True
EMAIL_FROM = '1736252185@qq.com' 
```

then ,you can use it  to send email

```python
# views.py
from django.core.mail import send_mail

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, settings.EMAIL_FROM, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form})
```

Gook luck！

you can foke my code sample:[mysite](https://github.com/hippieZhou/Python-Web-Every-Day/tree/master/13%20-%20django_by_example/01-mysite)

**Comment by k-a-suvorov** [comment]
Спасибо, Ваше письмо получено.
С уважением, Константин Суворов
