### ISSUE TITLE
Chapter 5: 'ascii' codec can't encode character '\xf6' in position 63: ordinal not in range(128)

### ISSUE THREAD

**Issue by MarvinKweyu** [PacktPublishing/Django-2-by-Example#24]
Anyone getting `UnicodeEncodeError` in Chapter05 during bookmarking an image?.I've got the same code as the guide but I get an error pointing to 
```python
 response = request.urlopen(image_url) # download 
```
My research online has born no fruit as I've been doing  `.encode('utf-8')` and `decode()` at places around the url. Is there a fix for this?

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
