### ISSUE TITLE
Chapter06, Incorrect position in r.zincrby 

### ISSUE THREAD

**Issue by BarabanovV** [PacktPublishing/Django-2-by-Example#28]
Chapter06/bookmarks/images/views.py/
Incorrect position of aruguments in r.zincrby 
now:
`r.zincrby('image_ranking', image.id, 1)`
correctly:
`r.zincrby('image_ranking', 1, image.id)`

example:
`ZINCRBY key increment member `

https://redis.io/commands/zincrby

**Comment by shubham763** [comment]
Hi @BarabanovV 

Thanks for highlighting this. I've updated the Github code file. I'd like to inform you that we have an updated version of this book available at the below link:
https://www.packtpub.com/web-development/django-3-by-example-third-edition

Regards,
Shubham
