### ISSUE TITLE
Chp 4: Facebook social authentication no longer works

### ISSUE THREAD

**Issue by jdblischak** [PacktPublishing/Django-2-by-Example#29]
The instructions for social authentication with Facebook no longer work because Facebook now [requires all apps to use HTTPS](https://developers.facebook.com/docs/facebook-login/security#https):

> On October 6, 2018, all apps will be required to use HTTPS.

Thus it results in the error message from Facebook:

```
Facebook has detected Bookmarks isn't using a secure connection to transfer information.
Until Bookmarks updates its security settings, you won't be able to use Facebook to log into it.
```

I tried following the advice from this [SO answer](https://stackoverflow.com/a/53120370) by changing the OAuth Redirect URI to `https://localhost:8000/social-auth/complete/facebook/`, but I got the same error.

**Comment by shubham763** [comment]
Hi @jdblischak 

Thanks for highlighting this. I'd like to inform you that we have an updated version of this book available at the below link:
https://www.packtpub.com/web-development/django-3-by-example-third-edition

Regards,
Shubham
