### ISSUE TITLE
Reverse for 'register' not found. 'register' is not a valid view function or pattern name?

### ISSUE THREAD

**Issue by fangchaooo** [PacktPublishing/Django-2-by-Example#3]
```python
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/account/login/

Django Version: 2.0.6
Python Version: 3.6.4
Installed Applications:
['account',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /home/fc/Documents/1111/bookmarks/account/templates/base.html, error at line 13
   Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
   3 : <html>
   4 : <head>
   5 :   <title>{% block title %}{% endblock %}</title>
   6 :   <link href="{% static "css/base.css" %}" rel="stylesheet">
   7 : </head>
   8 : <body>
   9 :   <div id="header">
   10 :     <span class="logo">Bookmarks</span>
   11 :     {% if request.user.is_authenticated %}
   12 :       <ul class="menu">
   13 :         <l i {% if section == " dashboard" %}class="selected"{% endif %}>
   14 :           <a href="{% url "dashboard" %}">My dashboard</a>
   15 :         </li>
   16 :         <li {% if section == "images" %}class="selected"{% endif %}>
   17 :           <a href="#">Images</a>
   18 :         </li>
   19 :         <li {% if section == "people" %}class="selected"{% endif %}>
   20 :           <a href="#">People</a>
   21 :         </li>
   22 :       </ul>
   23 :     {% endif %}


Traceback:

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  158.                 response = self.process_exception_by_middleware(e, request)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  156.                 response = response.render()

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/response.py" in render
  106.             self.content = self.rendered_content

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/response.py" in rendered_content
  83.         content = template.render(context, self._request)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
  175.                     return self._render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  155.             return compiled_parent._render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  67.                 result = block.nodelist.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/defaulttags.py" in render
  314.                 return nodelist.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/defaulttags.py" in render
  447.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/urls/base.py" in reverse
  90.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))

File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/urls/resolvers.py" in _reverse_with_prefix
  636.         raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /account/login/
Exception Value: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.

```

**views.py**
```python 
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .form import LoginForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})
```
**urls.py**

```python
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns =[
    # path('login/', views.user_login, name='login')
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
]
```

**Comment by praju89** [comment]
Hi fangchaooo,
Please follow all the instructions mentioned in the chapter and refer to the code files provided with the book. You should not face any difficulty.

**Comment by Pradhvan** [comment]
@praju89 I am facing the same issue and I did everything that the book told me to do. 

```BASH
Environment:


Request Method: GET
Request URL: http://localhost:8000/account/login/?next=/account/

Django Version: 2.1.3
Python Version: 3.7.1
Installed Applications:
['account.apps.AccountConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /home/pradhvan/django-tutorial/DjangoSocial/bookmarks/account/templates/base.html, error at line 13
   Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
   3 : <html>
   4 : <head>
   5 :   <title>{% block title %}{% endblock %}</title>
   6 :   <link href="{% static "css/base.css" %}" rel="stylesheet">
   7 : </head>
   8 : <body>
   9 :   <div id="header">
   10 :     <span class="logo">Bookmarks</span>
   11 :     {% if request.user.is_authenticated %}
   12 :       <ul class="menu">
   13 :         <l i {% if section == ' dashboard'%}class="selected"{% endif %}>
   14 :           <a href="{% url "dashboard" %}">My dashboard</a>
   15 :         </li>
   16 :         <li {% if section == "images" %}class="selected"{% endif %}>
   17 :           <a href="#">Images</a>
   18 :         </li>
   19 :         <li {% if section == "people" %}class="selected"{% endif %}>
   20 :           <a href="#">People</a>
   21 :         </li>
   22 :       </ul>
   23 :     {% endif %}


Traceback:

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  156.                 response = self.process_exception_by_middleware(e, request)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  154.                 response = response.render()

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/response.py" in render
  106.             self.content = self.rendered_content

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/response.py" in rendered_content
  83.         content = template.render(context, self._request)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  442.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/urls/base.py" in reverse
  90.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))

File "/home/pradhvan/django-auth/lib/python3.7/site-packages/django/urls/resolvers.py" in _reverse_with_prefix
  622.         raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /account/login/
Exception Value: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.

``

**Comment by Pradhvan** [comment]
@fangchaooo how did you resolve the issue ? if you did ?

**Comment by Jeswin17** [comment]
@Pradhvan  did you manage to resolve the issue ?

**Comment by Pradhvan** [comment]
@Jeswin17 yes I did

**Comment by imrangar304** [comment]
tell how please

**Comment by dlintin** [comment]
> tell how please

this how i resolve the issue, 

in urls.py if you use:  `path('login/', auth_views.LoginView.as_view(), name='login'),`
then you also need to use  `path('register/', user_views.register, name='register'),`

somehow this solve the issue.

**Comment by amabirbd** [comment]
> > tell how please
> 
> this how i resolve the issue,
> 
> in urls.py if you use: `path('login/', auth_views.LoginView.as_view(), name='login'),`
> then you also need to use `path('register/', user_views.register, name='register'),`
> 
> somehow this solve the issue.

Do you have any idea why that error occured? And any idea how to trobubleshoot that issue cause i am having the same problem.

**Comment by OpembaMathews** [comment]
I am also experiencing the same problem . `

Reverse for 'index' not found. 'index' is not a valid view function or pattern name.` 
Which book are you talking about anyways. Maybe it could help

**Comment by PaulinaKas** [comment]
> I am also experiencing the same problem . `
> 
> Reverse for 'index' not found. 'index' is not a valid view function or pattern name.`
> Which book are you talking about anyways. Maybe it could help

The book is 'Django-2-by-Example'

**Comment by PaulinaKas** [comment]
> Do you have any idea why that error occured? And any idea how to trobubleshoot that issue cause i am having the same problem.

In my error case "Reverse for 'register' not found. 'register' is not a valid view function or pattern name." the solution was not adding new url path like in below proposition:
> this how i resolve the issue,
> in urls.py if you use: `path('login/', auth_views.LoginView.as_view(), name='login'),`
> then you also need to use `path('register/', user_views.register, name='register'),`
> somehow this solve the issue.

but removing code lines connected with "register". I copied too many code lines from one of this book's chapters to _bookmarks/account/templates/registration/login.html_ and thereupon I had code like: 
`{% else %}
    <p>Please, use the following form to log-in. If you don't have an account <a href="{% url "register" %}">register here</a></p>
  {% endif %}` which I minimised to `<p>Please, use the following form to log-in.</p>`

Therefore I truly recommend to check your .html files in search of some "register"s.

**Comment by akanz** [comment]
okay , I had the same issue too while trying to view my home page. the problem is likely from your urls.py . 

from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name = 'home')
]
make sure to specify the name of the view. hope this helps

**Comment by geniemay** [comment]
Remove href to {% url "register" %} from login.html on this examples step. There was your copy-past result probably.

**Comment by J-Nz** [comment]
> > tell how please
> 
> this how i resolve the issue,
> 
> in urls.py if you use: `path('login/', auth_views.LoginView.as_view(), name='login'),`
> then you also need to use `path('register/', user_views.register, name='register'),`
> 
> somehow this solve the issue.

my mistake was instead of typing this:
path('register/', user_views.register, name='register')
I was using this:
path("register", views.register, name="index")
the name="index" was obviously wrong!

**Comment by Marcel0o** [comment]
@praju89 Even if you follow the book you still get the same error

**Comment by Marcel0o** [comment]
> ```python
> Environment:
> 
> 
> Request Method: GET
> Request URL: http://127.0.0.1:8000/account/login/
> 
> Django Version: 2.0.6
> Python Version: 3.6.4
> Installed Applications:
> ['account',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> Template error:
> In template /home/fc/Documents/1111/bookmarks/account/templates/base.html, error at line 13
>    Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
>    3 : <html>
>    4 : <head>
>    5 :   <title>{% block title %}{% endblock %}</title>
>    6 :   <link href="{% static "css/base.css" %}" rel="stylesheet">
>    7 : </head>
>    8 : <body>
>    9 :   <div id="header">
>    10 :     <span class="logo">Bookmarks</span>
>    11 :     {% if request.user.is_authenticated %}
>    12 :       <ul class="menu">
>    13 :         <l i {% if section == " dashboard" %}class="selected"{% endif %}>
>    14 :           <a href="{% url "dashboard" %}">My dashboard</a>
>    15 :         </li>
>    16 :         <li {% if section == "images" %}class="selected"{% endif %}>
>    17 :           <a href="#">Images</a>
>    18 :         </li>
>    19 :         <li {% if section == "people" %}class="selected"{% endif %}>
>    20 :           <a href="#">People</a>
>    21 :         </li>
>    22 :       </ul>
>    23 :     {% endif %}
> 
> 
> Traceback:
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   35.             response = get_response(request)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   158.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   156.                 response = response.render()
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/response.py" in render
>   106.             self.content = self.rendered_content
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/response.py" in rendered_content
>   83.         content = template.render(context, self._request)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/backends/django.py" in render
>   61.             return self.template.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
>   175.                     return self._render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in _render
>   167.         return self.nodelist.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/loader_tags.py" in render
>   155.             return compiled_parent._render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in _render
>   167.         return self.nodelist.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/loader_tags.py" in render
>   67.                 result = block.nodelist.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/defaulttags.py" in render
>   314.                 return nodelist.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/template/defaulttags.py" in render
>   447.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/urls/base.py" in reverse
>   90.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
> 
> File "/home/fc/.local/share/virtualenvs/1111-oxI__AFh/lib/python3.6/site-packages/django/urls/resolvers.py" in _reverse_with_prefix
>   636.         raise NoReverseMatch(msg)
> 
> Exception Type: NoReverseMatch at /account/login/
> Exception Value: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
> ```
> 
> **views.py**
> 
> ```python
> from django.shortcuts import render
> from django.http import HttpResponse
> from django.contrib.auth import authenticate, login
> from .form import LoginForm
> from django.contrib.auth.decorators import login_required
> # Create your views here.
> 
> def user_login(request):
>     if request.method == 'POST':
>         form = LoginForm(request.POST)
>         if form.is_valid():
>             cd = form.cleaned_data
>             user = authenticate(request,
>                                 username=cd['username'],
>                                 password=cd['password'])
>             if user is not None:
>                 if user.is_active:
>                     login(request, user)
>                     return HttpResponse('Authenticated '\
>                                         'successfully')
>                 else:
>                     return HttpResponse('Disabled account')
>             else:
>                 return HttpResponse('Invalid login')
>     else:
>         form = LoginForm()
>     return render(request, 'account/login.html', {'form': form})
> 
> @login_required
> def dashboard(request):
>     return render(request, 'account/dashboard.html', {'section': 'dashboard'})
> ```
> 
> **urls.py**
> 
> ```python
> from django.urls import path
> from django.contrib.auth import views as auth_views
> from . import views
> 
> urlpatterns =[
>     # path('login/', views.user_login, name='login')
>     path('login/', auth_views.LoginView.as_view(), name='login'),
>     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
>     path('', views.dashboard, name='dashboard'),
> ]
> ```

We're you able to solve it

**Comment by migenru** [comment]
The problem exists
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.

**Comment by imvdharmesh** [comment]
> > tell how please
> 
> this how i resolve the issue,
> 
> in urls.py if you use: `path('login/', auth_views.LoginView.as_view(), name='login'),`
> then you also need to use `path('register/', user_views.register, name='register'),`
> 
> somehow this solve the issue.

Thanks

**Comment by Damu2509** [comment]
**see this error** : In template /home/fc/Documents/1111/bookmarks/account/templates/base.html, error at line 13

The reason is, you have to specify the url literal along with the 'app_name' of your project .

**Ex**:Use app_name in urls.py file and use this app_name along with the name specified in urls.py to load the url in template
                  [ href = " url  'app_name:dashboard' %} ]

**Note** : colon[ : ] should be specified in between 'app_name' and 'name specified in urls.py' file
 
In urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'demo'.        # Add this to your urls.py file according to the app name that you created for your project
urlpatterns =[
    # path('login/', views.user_login, name='login')
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
]

  Then you have to use 

   14 :           <a href="{% url "demo:dashboard" %}">My dashboard</a>.     # add this in your templates file so as to load url

The reason behind the usage of  'app_name' is, django doesn't know which app url literal to load as you have multiple apps in your project . So, it's better specify 'app_name' for every urls.py file in an app of a project

Trust me ! It works a lot better than before

**Comment by mejl** [comment]
I'm getting that error and I have this code in

 urls.py
```
from django.urls import path


from . import views

app_name = 'users'
urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/register/', views.register, name='register'),
]
```

**Comment by drakmirr** [comment]
> Remove href to {% url "register" %} from login.html on this examples step. There was your copy-past result probably.

really works, thanks

**Comment by lappiahnuamah** [comment]
Please what's the name of the book
and mine is still not working

**Comment by lappiahnuamah** [comment]
Oh guys, I think I have been able to rectify mine. All you need to do is to be mindful  of the name you will use in the urls.py so that when you're referencing back in the template file, you make sure to use the same name you used at the urls.py...
Thanks
