### ISSUE TITLE
Chp 4: Updates to Twitter social authentication instructions

### ISSUE THREAD

**Issue by jdblischak** [PacktPublishing/Django-2-by-Example#30]
I was able to get the social authentication via Twitter working. However, Twitter has made some changes since the publication of this book:

* `apps.twitter.com` was replaced by `developer.twitter.com` (it of course redirects to this new URL)
* The app name has to be unique. When I tried using "Bookmarks", I received the error "appName: Bookmarks is already taken for Name"
* There is now a checkbox [Enable Sign in with Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/log-in-with-twitter/login-in-with-twitter) that needs to be checked
* It is now required to describe how the app will be used (only visible to Twitter employees)

**Comment by deepesh-packt** [comment]
Hey @jdblischak ,

Thanks for highlighting this. I'd like to inform you that we have an updated version of this book available at the below link: 
https://www.packtpub.com/web-development/django-3-by-example-third-edition

Regards,
Deepesh
