### ISSUE TITLE
Chp 4: Update to Google+ social authentication instructions

### ISSUE THREAD

**Issue by jdblischak** [PacktPublishing/Django-2-by-Example#31]
I was able to get the social authentication via Google+ working. However, there was one significant change: before I could add the redirect URI `http://mysite.com:8000/social-auth/complete/google-oauth2/`, I first add to add `mysite.com` to the list of [authorized domains](https://support.google.com/cloud/answer/6158849?hl=en#authorized-domains). This can be done on the "Oauth consent screen" page.

**Comment by deepesh-packt** [comment]
Hey @jdblischak ,

Thanks for highlighting this. I'd like to inform you that we have an updated version of this book available at the below link:
https://www.packtpub.com/web-development/django-3-by-example-third-edition

Regards,
Deepesh
