### ISSUE TITLE
Chapter 12. detail_route deprecated from DRF 3.8

### ISSUE THREAD

**Issue by HankSerg** [PacktPublishing/Django-2-by-Example#36]
Chapter 12 uses the @detail_route decorator.  It is outdated in the latest versions of DRF.
It is used here : /courses/api/views.py in CourseViewSet class.
Example: `from rest_framework.decorators import detail_route`

**Comment by dstanek** [comment]
This can be confirmed in the [3.8 announcement](https://www.django-rest-framework.org/community/3.8-announcement/#deprecations).

The real question is should the code here change and not match the book? If the answer is "yes" then we should add some comments in the code explaining why it doesn't match the book. I think this is what we should do.

If nothing else we may want to add a TODO for the next version fof the book and add a comment in the code saying parts have been deprecated.

Either way I think we need to be clear to future readers that may have the older copy of the book.
