### ISSUE TITLE
Chapter 01 with Django 3

### ISSUE THREAD

**Issue by ElenaBochkova** [PacktPublishing/Django-2-by-Example#39]
When I'm using class PostListView in the end of chapter 01,  I have a problem: at the bottom of http://localhost:8000/blog/ numbers of pages with links dissappear. I see only "Page of" there.
Is it a problem of Django 3?
Can I add something to class PostListView to solve this problem?

**Comment by kenanking** [comment]
You need to replace `page=posts` with `page=page_obj` in **list.html**.
```django
{% include "pagination.html" with page=page_obj %}
```
