### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by olishchuk1** [PacktPublishing/Django-2-by-Example#49]
https://github.com/PacktPublishing/Django-2-by-Example/blob/e81223688f43ec71a2386d6640a5dcb99b16083d/Chapter05/bookmarks/images/static/js/bookmarklet.js#L72

Change 'ocurred' to 'occurred'

**Comment by deepesh-packt** [comment]
Hey @olishchuk1 
Thanks for highlighting this typo. I've fixed this typo. You can check using the below link:
https://github.com/PacktPublishing/Django-2-by-Example/blob/dd5893593a112561c1494ccf27c5fa00cf64524b/Chapter05/bookmarks/images/static/js/bookmarklet.js#L72
