### ISSUE TITLE
chapter 1: model manager does not work.

### ISSUE THREAD

**Issue by DamnFilthy** [PacktPublishing/Django-2-by-Example#50]
when **adding an article through the admin panel, you need to change the status to "published"** then your code works!

**or by default assign the desired status:**

```
status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='published')
```
Your manager is looking for only published articles, but by default there is a different status(**default='draft'**), through the admin panel you can set the desired status of the article, but when users write articles, the status will be generated automatically and then not a single article will fall under your search!

good tutorial! thanks

**Comment by DamnFilthy** [comment]
> Hello, I found out that in the **first chapter** the technique of **creating your own model manager does not work**.
> You create class:
> 
> ```
> class PublishedManager(models.Manager): 
>     def get_queryset(self): 
>         return super(PublishedManager, self).get_queryset().filter(status='published')
> ```
> 
> and use it:
> `published = PublishedManager()`
> 
> if you work according to your method, then not a single article will be displayed on the main page, but if you display records on the main page using the standard method, then you still cannot open the full article record, there will be an exception - the page was not found.
> 
> For everything to work correctly and to display articles from the database, as well as open the full version of the article, you must use a standard database manager.
> 
> in this case:
> `objects = models.Manager()`
> `object_list = Post.objects.all()`
> 
> and in this:
> 
> ```
>    post = get_object_or_404(Post, slug=post,
>                                    status='published',
>                                    publish__year=year,
>                                    publish__month=month,
>                                    publish__day=day)
> ```
> 
> you need to delete `status='published',`
> 
> **so correct entry:**
> 
> ```
>    post = get_object_or_404(Post, slug=post,
>                                    publish__year=year,
>                                    publish__month=month,
>                                    publish__day=day)
> ```
> 
> and accordingly, in all other cases of accessing the database, **you must use the default manager**
> 
> **`Post.objects.all()`**
> 
> _I am studying from your book (and I like everything), but this method does not work, I had to use the standard method, but I would really like to know why this is happening? why does this method mentioned in the book not work?_
> 
> **I will be very grateful if you explain to me.**

**Comment by packt-pradeeps** [comment]
Thanks for pointing this out.
