### ISSUE TITLE
Exception Value:	 Manager isn't accessible via Post instances

### ISSUE THREAD

**Issue by flakesrc** [PacktPublishing/Django-2-by-Example#6]
I do not know why this error is occurring, I did everything as the book shows.

https://github.com/marcoscoder/my-blog/releases/tag/1

**Comment by Jeanca7** [comment]
Hi @praju89, 
I'm working on the Like/Dislike functionality using ajax (chapter 5) and I'm having a parsing error: Unexpected %.
`<script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
       });
  `</script>[](url)``
