### ISSUE TITLE
Recommended django-taggit version, 0.22.2, is incompatible with Django 2.1

### ISSUE THREAD

**Issue by meli-lewis** [PacktPublishing/Django-2-by-Example#7]
The book recommends django-taggit version 0.22.2, but because Django 2.1 removed support for `Widget.render()` without the `renderer` argument, the two are incompatible, and attempting to open a post returns the error `render() got an unexpected keyword argument 'renderer'`.

This issue is resolved in django-taggit version 0.23: https://github.com/alex/django-taggit/pull/534.

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists
